server:
  port: 8082

spring:
  application:
    name: BILL-PAY-STATUS
  datasource:
    url: jdbc:oracle:thin:@//10.230.1.211:1521/nagadprim
    username: TECH_PM_NAZIM_STG_TW190182
    password: NoBody
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8162/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
