server:
  port: 9192

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: BILL-PAY-TXN-STATUS
          uri: lb://BILL-PAY-TXN-STATUS
          predicates:
            - Path=/api/v1/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8162/eureka/